import './quote.css'
import React, { Component } from 'react'
const { GoogleSpreadsheet } = require('google-spreadsheet');


const creds = require('../../../credentials.json')

let row, element;
export default class Quote extends Component {
    state = {}

    componentDidMount() {
        this.getSheetValues();
    }

    checkForRowNotOne = (row) => {
        if (row === 1) {
            return row + 1
        } else {
            return row
        }
    }
    getRandomRow = (rowCount) => {
        row = Math.floor(Math.random() * Math.floor(rowCount))
        this.checkForRowNotOne(row)
        return row
    }
    
    getSheetValues = async () => {
        try {
            const doc = new GoogleSpreadsheet('1-4M0vr8l5qvwvcpzkvlm4jZ1pgfAIZykw5Gx5-l3eSY');

            // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
            await doc.useServiceAccountAuth({
                // env var values are copied from service account credentials generated by google
                // see "Authentication" section in docs for more info
                client_email: creds.client_email,
                private_key: creds.private_key,
            });

            await doc.loadInfo(); // loads document properties and worksheets
            const sheet = doc.sheetsByIndex[0];
            let row = this.getRandomRow(sheet.rowCount);
            const rows = await sheet.getRows()
            let author = rows[row].Author
            let quote = rows[row].Quote
            element = `"${quote}" by ${author}`
            this.setState({
                Quote: element
            })
        } catch(err) {
            element = `"If talent's a kind of natural energy, doesn't it have to find an outlet?" by Haruki Murakami`
            this.setState({
                Quote: element
            })
        }
    }

    render() {
        return (
            <div>
                <h2 className={'quote'}>{this.state.Quote}</h2>
            </div>
        )
    }
    
}